name: Release actions

on:
  push:
    tags:
    - 'v*'

jobs:

  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - uses: actions/checkout@master
    - name: Archive Release
      uses: thedoctor0/zip-release@0.7.0
      with:
        type: 'zip'
        filename: '.github/releases/hass-jellyfish-lighting.zip'
        exclusions: '.devcontainer/\* .github/\* .vscode/\* \*.git\* requirements_dev.txt setup.cfg CONTRIBUTING.md'
    - uses: actions/checkout@v2
    - uses: ncipollo/release-action@v1.12.0
      with:
        artifacts: ".github/releases/hass-jellyfish-lighting.zip"
        draft: true
        generateReleaseNotes: true
        makeLatest: true