name: Release actions

on:
  push:
    tags:
    - 'v*'

jobs:

  create-release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - uses: actions/checkout@v2
    - name: Archive Release
      uses: thedoctor0/zip-release@0.7.0
      with:
        type: 'zip'
        directory: 'custom_components/jellyfish_lighting'
        filename: 'jellyfish_lighting.zip'
    - uses: ncipollo/release-action@v1.12.0
      with:
        artifacts: 'custom_components/jellyfish_lighting/jellyfish_lighting.zip'
        draft: true
        generateReleaseNotes: true
        makeLatest: true