name: Releases

on:
  push:
    tags:
    - 'v*'

jobs:

  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - uses: actions/checkout@v2
    - uses: ncipollo/release-action@v1.12.0
      with:
        artifacts: "releases/hass-jellyfish-lighting.zip"
        bodyFile: "body.md"
        draft: true
        generateReleaseNotes: true
        makeLatest: true